vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /uploads/product
            upload_destination: '%kernel.project_dir%/public/uploads/product'
        blog_image:
            uri_prefix: /uploads/blog
            upload_destination: '%kernel.project_dir%/public/uploads/blog'
        aboutUs_image:
            uri_prefix: /uploads/aboutUs
            upload_destination: '%kernel.project_dir%/public/uploads/aboutUs'
        homeBlog_image:
            uri_prefix: /uploads/homeBlog
            upload_destination: '%kernel.project_dir%/public/uploads/homeBlog'
        banner_image:
            uri_prefix: /uploads/banner
            upload_destination: '%kernel.project_dir%/public/uploads/banner'
        secondBanner_image:
            uri_prefix: /uploads/secondBanner
            upload_destination: '%kernel.project_dir%/public/uploads/secondBanner'
        category_image:
            uri_prefix: /uploads/category
            upload_destination: '%kernel.project_dir%/public/uploads/category'