vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
        #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blog_image:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
        #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        aboutUs_image:
            uri_prefix: assets/images/banner
            upload_destination: '%kernel.project_dir%/public/assets/images/banner'
        #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        homeBlog_image:
            uri_prefix: assets/images/banner
            upload_destination: '%kernel.project_dir%/public/assets/images/banner'
            #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        banner_image:
            uri_prefix: assets/images/slider
            upload_destination: '%kernel.project_dir%/public/assets/images/slider'
            #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        secondBanner_image:
            uri_prefix: assets/images/bg
            upload_destination: '%kernel.project_dir%/public/assets/images/bg'
            #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        category_image:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
        #            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer