# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_dir_product: '%kernel.project_dir%/public/uploads/product'
    upload_dir_category: '%kernel.project_dir%/public/uploads/category'
    upload_dir_aboutUs: '%kernel.project_dir%/public/uploads/aboutUs'
    upload_dir_blog: '%kernel.project_dir%/public/uploads/blog'
    upload_dir_homeBlog: '%kernel.project_dir%/public/uploads/homeBlog'
    upload_dir_banner: '%kernel.project_dir%/public/uploads/banner'
    upload_dir_secondBanner: '%kernel.project_dir%/public/uploads/secondBanner'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
#            $uploadDir: '%upload_dir%'
            $stripeSk: "%env(STRIPE_SK)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
